default_environment: default

environments:
  local:
    connections:
      duckdb:
        - name: duckdb-default
          path: duckdb.db

  default:
    connections:
      motherduck:
        - name: duckdb-default
      chess:
        - name: chess-default
          players:
            - MagnusCarlsen
            - Hikaru
